# --- !Ups

create table "CATEGORY" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
create table "DOCUMENT" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"category_id" BIGINT NOT NULL,"actual_version_id" BIGINT);
create table "VERSION" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"document_id" BIGINT NOT NULL,"date" DATE NOT NULL,"version" VARCHAR NOT NULL,"file" BLOB NOT NULL);
alter table "DOCUMENT" add constraint "CATEGORY_FK" foreign key("category_id") references "CATEGORY"("id") on update NO ACTION on delete NO ACTION;
alter table "VERSION" add constraint "DOCUMENT_FK" foreign key("document_id") references "DOCUMENT"("id") on update NO ACTION on delete NO ACTION;
insert into "CATEGORY" values (1, 'Миграционные');

# --- !Downs

alter table "DOCUMENT" drop constraint "CATEGORY_FK";
alter table "VERSION" drop constraint "DOCUMENT_FK";
drop table "CATEGORY";
drop table "DOCUMENT";
drop table "VERSION";

